/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package mdiform;

import java.awt.Toolkit;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class frmNuevoEditar_IVA extends javax.swing.JDialog {
    
    public Integer CodIVA;
    public String NomIVA;
    public String IVA;
    public Integer Estado; // 0=Editar 1=Nuevo 

    /**
     * Creates new form frmNuevoEditar_IVA
     */
    public frmNuevoEditar_IVA(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocation((Toolkit.getDefaultToolkit().getScreenSize().width)/2 - getWidth()/2, (Toolkit.getDefaultToolkit().getScreenSize().height)/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        edtNomIVA = new javax.swing.JTextField();
        edtIVA = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo IVA");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Descripción");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel2.setText("IVA %");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mdiform/Icons/Checkmark_16px.png"))); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mdiform/Icons/Cancel_16px.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, 30));
        jPanel1.add(edtNomIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 270, -1));
        jPanel1.add(edtIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 110, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 360, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 386, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Guardar Cambios IVAS
        
        // Comprobar Valores
        if (edtNomIVA.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debes de introducir una descripción", "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            edtNomIVA.setFocusable(true);
            return;
        }

        if (edtIVA.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debes de introducir el IVA", "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            edtIVA.setFocusable(true);
            return;
        }
        
        String sIVA = edtIVA.getText().toString();
        Integer IVA = Integer.valueOf(sIVA);
        String NomIVA = edtNomIVA.getText().toString();
        
        Guardar_IVA(NomIVA, IVA);
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
         // Comprobar el Estado
        if (Estado == 0){
           edtNomIVA.setText(NomIVA);
           edtIVA.setText(IVA);
        }
    }//GEN-LAST:event_formComponentShown
    private void Guardar_IVA(String NomIVA, Integer Iva) {
       // Muestra la información del cliente para poder editarlo
        try {
            // Send Query
            String Quotes = "\"";

            Connection connection = null;
            Statement stmt = null;
            CallableStatement cs = null;
            ResultSet rs = null;

            // Comprobar el Estado 0=Editar 1=Nuevo
            String SQL;
            if (Estado == 1){
                SQL = "{call XGESTION_PKG.INSERTAR_IVA(?, ?)}";
            }else{
                SQL = "{call XGESTION_PKG.ACTUALIZAR_IVA(?, ?, ?)}";
            }

            connection = DriverManager.getConnection(NewJFrame.dbURL, NewJFrame.username, NewJFrame.password);
            stmt = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
            cs = connection.prepareCall(SQL);        
            
            
            /***XGESTION_PKG.INSERTAR_IVA
             * p_nomiva   IN IVAS.NOMIVA%TYPE,
               p_iva      IN IVAS.IVA%TYPE
             */
            
            if (Estado == 1){
                cs.setString(1, NomIVA);
                cs.setInt(2, Iva);
            }
            else{
                
            /***XGESTION_PKG.ACTUALIZAR_IVA
             *p_codiva   IN IVAS.CODIVA%TYPE,
              p_nomiva   IN IVAS.NOMIVA%TYPE,
              p_iva      IN IVAS.IVA%TYPE)
              */
            
                cs.setInt(1, CodIVA);    
                cs.setString(2, NomIVA);
                cs.setInt(3, Iva);    
                
            }
            
            cs.execute();

            cs.close();
           
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage().toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNuevoEditar_IVA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNuevoEditar_IVA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNuevoEditar_IVA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNuevoEditar_IVA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmNuevoEditar_IVA dialog = new frmNuevoEditar_IVA(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField edtIVA;
    private javax.swing.JTextField edtNomIVA;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
